name: custom_carousel
description: Custom Carousel is a package that comes with the idea of making life easier for the developer who needs to add a carousel to his flutter project. We are currently at version 0.0.1
version: 0.0.1
repository: https://github.com/Leonardo1952/custom_carousel_package

environment:
  sdk: '>=2.18.6 <3.0.0'
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0


flutter:
